INSERT INTO phrases VALUES(NULL, 'Salam', 'Hello');
INSERT INTO phrases VALUES(NULL, 'Chetori?', 'How are you?');
INSERT INTO phrases VALUES(NULL, 'Khub\'am', 'I\'m good');
INSERT INTO phrases VALUES(NULL, 'Mersi', 'Thank you');
INSERT INTO phrases VALUES(NULL, 'Kheili khub\'am', 'I\'m very good');
INSERT INTO phrases VALUES(NULL, 'Khub nist\'am', 'I\'m not good');
INSERT INTO phrases VALUES(NULL, 'Bad nist\'am', 'I\'m not bad');
INSERT INTO phrases VALUES(NULL, 'aalee', 'awesome');
INSERT INTO phrases VALUES(NULL, 'Sobh bekheir', 'Good morning');
INSERT INTO phrases VALUES(NULL, 'Rooz bekheir', 'Good day');
INSERT INTO phrases VALUES(NULL, 'Asre bekheir', 'Good afternoon');
INSERT INTO phrases VALUES(NULL, 'Shab bekheir', 'Good night');
INSERT INTO phrases VALUES(NULL, 'khodafess', 'goodbye');
INSERT INTO phrases VALUES(NULL, 'feilaan', 'bye for now');
INSERT INTO phrases VALUES(NULL, 'be omeed\'e didar', 'hope to see you again');
INSERT INTO phrases VALUES(NULL, 'didar', 'to see');
INSERT INTO phrases VALUES(NULL, 'omeed', 'hope');
INSERT INTO phrases VALUES(NULL, 'taa ba-d', 'see you later (until later)');
INSERT INTO phrases VALUES(NULL, 'feirda', 'tomorrow');
INSERT INTO phrases VALUES(NULL, 'taa feirda', 'see you tomorrow (until tomorrow)');
INSERT INTO phrases VALUES(NULL, 'Esme man Matt hast', 'My name is Matt');
INSERT INTO phrases VALUES(NULL, 'Khosh vakt\'am', 'Nice to meet you');
INSERT INTO phrases VALUES(NULL, 'Esme to chi\'ye?', 'What is your name?');
INSERT INTO phrases VALUES(NULL, 'Che khabaar?', 'What\'s up?');
INSERT INTO phrases VALUES(NULL, 'To ahle koja hasti?', 'Where are you from?');
INSERT INTO phrases VALUES(NULL, 'Man as Canada hastam', 'I am from Canada');
INSERT INTO phrases VALUES(NULL, 'Manam as Iran hastam', 'I am also from Iran');
INSERT INTO phrases VALUES(NULL, 'Man as Montreal nistam', 'I am not from Montreal');
INSERT INTO phrases VALUES(NULL, 'Man dar Montreal zendeghi mikhonam', 'I live in Montreal');
INSERT INTO phrases VALUES(NULL, 'zendeghi', 'life');
INSERT INTO phrases VALUES(NULL, 'dar', 'in');
INSERT INTO phrases VALUES(NULL, 'mikhonam', 'I do');
INSERT INTO phrases VALUES(NULL, 'To koja zendeghi mikhoni?', 'Where do you live?');
INSERT INTO phrases VALUES(NULL, 'asand', 'excellent/well done');
INSERT INTO phrases VALUES(NULL, 'hala', 'now');
INSERT INTO phrases VALUES(NULL, 'boland', 'tall');
INSERT INTO phrases VALUES(NULL, 'kootah', 'short');
INSERT INTO phrases VALUES(NULL, 'ziba', 'beautiful');
INSERT INTO phrases VALUES(NULL, 'bahoosh', 'smart');
INSERT INTO phrases VALUES(NULL, 'laghar', 'thin');
INSERT INTO phrases VALUES(NULL, 'chagh', 'fat');
INSERT INTO phrases VALUES(NULL, 'khoshtip', 'handsome');
INSERT INTO phrases VALUES(NULL, 'sarboland', 'proud');
INSERT INTO phrases VALUES(NULL, 'raahat assoodeh', 'relieved');
INSERT INTO phrases VALUES(NULL, 'ahmagh', 'silly');
INSERT INTO phrases VALUES(NULL, 'seposkuzar', 'thankful');
INSERT INTO phrases VALUES(NULL, 'barodar', 'brother');
INSERT INTO phrases VALUES(NULL, 'khaheir', 'sister');
INSERT INTO phrases VALUES(NULL, 'madeir', 'mother');
INSERT INTO phrases VALUES(NULL, 'pedar', 'father');
INSERT INTO phrases VALUES(NULL, 'shoheir', 'husband');
INSERT INTO phrases VALUES(NULL, 'zan', 'woman/wife');
INSERT INTO phrases VALUES(NULL, 'pesar', 'boy/son');
INSERT INTO phrases VALUES(NULL, 'dokhtar', 'girl/daughter');
INSERT INTO phrases VALUES(NULL, 'Madeir\'e man', 'My mother');
INSERT INTO phrases VALUES(NULL, 'Pedar\'e to', 'Your father');
INSERT INTO phrases VALUES(NULL, 'In khaheir\'e man', 'This is my sister');
INSERT INTO phrases VALUES(NULL, 'Ishun pedare manand', 'He is my father');
INSERT INTO phrases VALUES(NULL, 'Esmesh Lodan\'e', 'his/her name is');
INSERT INTO phrases VALUES(NULL, 'Esmeshun Mariam\'e', 'His/her name is Mariam(formal)');
INSERT INTO phrases VALUES(NULL, 'Man ye khaheir daar\'am', 'I have a sister');
INSERT INTO phrases VALUES(NULL, 'Man ye barodar daar\'am, esmesh Mark hast', 'I have a brother, his name is Mark');
INSERT INTO phrases VALUES(NULL, 'Esmashun Sara va Mariam hast', 'Their names are Sara and Mariam');
INSERT INTO phrases VALUES(NULL, 'Man mo\'allem hastam', 'I am a teacher');
INSERT INTO phrases VALUES(NULL, 'shagheird', 'student');
INSERT INTO phrases VALUES(NULL, 'mohandess', 'engineer');
INSERT INTO phrases VALUES(NULL, 'vakeel', 'lawyer');
INSERT INTO phrases VALUES(NULL, 'nevisande', 'writer');
INSERT INTO phrases VALUES(NULL, 'metmar', 'architect');
INSERT INTO phrases VALUES(NULL, 'To che kar\'e hasti?', 'What do you do for work?');
INSERT INTO phrases VALUES(NULL, 'To chetor?', 'How about you?');
INSERT INTO phrases VALUES(NULL, 'Koja kar mikhoni?', 'Where do you work?');
INSERT INTO phrases VALUES(NULL, 'kar', 'work');
INSERT INTO phrases VALUES(NULL, 'mikhonam', 'I do');
INSERT INTO phrases VALUES(NULL, 'edare', 'office');
INSERT INTO phrases VALUES(NULL, 'kar-khune', 'factory');
INSERT INTO phrases VALUES(NULL, 'resturaan', 'restaurant');
INSERT INTO phrases VALUES(NULL, 'bimaarestan', 'hospital');
INSERT INTO phrases VALUES(NULL, 'Man dar edare kar mikhonam', 'I work in an office');
INSERT INTO phrases VALUES(NULL, 'Man dar kar-khune kar mikhonam', 'I work in a factory');
INSERT INTO phrases VALUES(NULL, 'Kar\'e to doost daar\'i?', 'Do you like your job?');
INSERT INTO phrases VALUES(NULL, 'Bale, karam\'o doost daar\'am', 'Yes, I like my job');
INSERT INTO phrases VALUES(NULL, 'Na, karam\'o doost nadaar\'am', 'No, I don\'t like my job');
INSERT INTO phrases VALUES(NULL, 'Man kar nemikhonam', 'I don\'t work');
INSERT INTO phrases VALUES(NULL, 'Man bikaar\'am', 'I\'m without a job');
INSERT INTO phrases VALUES(NULL, 'Kar mikhonam', 'I work');
INSERT INTO phrases VALUES(NULL, 'Man basneshaste hastam', 'I am retired');
INSERT INTO phrases VALUES(NULL, 'shocolate', 'chocolate');
INSERT INTO phrases VALUES(NULL, 'tabiat', 'nature');
INSERT INTO phrases VALUES(NULL, 'moosighri', 'music');
INSERT INTO phrases VALUES(NULL, 'Man shocolate doost daar\'am', 'I like chocolate');
INSERT INTO phrases VALUES(NULL, 'Man tabiat kheili doost daar\'am', 'I really like nature');
INSERT INTO phrases VALUES(NULL, 'Man Charlie Chaplin\'o doost daar\'am', 'I like Charlie Chaplin');
INSERT INTO phrases VALUES(NULL, 'Doost daar\'am film bebinam', 'I like to watch movies');
INSERT INTO phrases VALUES(NULL, 'Doost daar\'am ketaab bekhunam', 'I like to read books');
INSERT INTO phrases VALUES(NULL, 'Doost daar\'am varzesh bokonam', 'I like exercising');
INSERT INTO phrases VALUES(NULL, 'Doost daar\'am shocolate bokhoram', 'I like to eat chocolate');
INSERT INTO phrases VALUES(NULL, 'Doost daar\'am Farsi yaad begiram', 'I like to learn Persian');
INSERT INTO phrases VALUES(NULL, 'Haale shoma chetore?', 'How are you? (formal)');
INSERT INTO phrases VALUES(NULL, 'Chi doost daar\'i?', 'What do you like?');
INSERT INTO phrases VALUES(NULL, 'Esm\'am Matt\'e', 'My name is Matt (short-form)');
INSERT INTO phrases VALUES(NULL, 'Esm\'am Layla\'st', 'My name is Layla (short-form)');
INSERT INTO phrases VALUES(NULL, 'khaale', 'aunt (mother\'s sister)');
INSERT INTO phrases VALUES(NULL, 'dai', 'uncle (mother\'s brother)');
INSERT INTO phrases VALUES(NULL, 'ame', 'aunt (father\'s sister)');
INSERT INTO phrases VALUES(NULL, 'amu', 'uncle (father\'s brother)');
INSERT INTO phrases VALUES(NULL, 'koja', 'where');
INSERT INTO phrases VALUES(NULL, 'chera', 'why');
INSERT INTO phrases VALUES(NULL, 'ki', 'who');
INSERT INTO phrases VALUES(NULL, 'chi', 'what');
INSERT INTO phrases VALUES(NULL, 'chetor', 'how');
INSERT INTO phrases VALUES(NULL, 'kay', 'when');
INSERT INTO phrases VALUES(NULL, 'kodoom', 'which');
INSERT INTO phrases VALUES(NULL, 'Koja\'i?', 'Where are you?');
INSERT INTO phrases VALUES(NULL, 'Chera na?', 'Why not?');
INSERT INTO phrases VALUES(NULL, 'In kie?', 'Who is this?');
INSERT INTO phrases VALUES(NULL, 'Chetor pish mire?', 'How\'s it going?');
INSERT INTO phrases VALUES(NULL, 'roshan bolonde', 'blonde');
INSERT INTO phrases VALUES(NULL, 'sabzeh', 'brunette');
INSERT INTO phrases VALUES(NULL, 'moaafegh', 'agreeable');
INSERT INTO phrases VALUES(NULL, 'shoja', 'brave');
INSERT INTO phrases VALUES(NULL, 'aroom', 'calm');
INSERT INTO phrases VALUES(NULL, 'khoshhall', 'happy');
INSERT INTO phrases VALUES(NULL, 'mehraboon', 'nice');
INSERT INTO phrases VALUES(NULL, 'por energie', 'energetic');
INSERT INTO phrases VALUES(NULL, 'zabaan', 'language');
INSERT INTO phrases VALUES(NULL, 'Farsi sohbat mikon\'am', 'I speak Persian');
INSERT INTO phrases VALUES(NULL, 'To Farsi sohbat mikon\'i?', 'Do you speak Persian?');
INSERT INTO phrases VALUES(NULL, 'Farsi sohbat nemikon\'am', 'I don\'t speak Persian');
INSERT INTO phrases VALUES(NULL, 'Kami farsi sohbat mikon\'am', 'I speak a bit of Persian');
INSERT INTO phrases VALUES(NULL, 'englisi', 'english');
INSERT INTO phrases VALUES(NULL, 'faransavi', 'french');
INSERT INTO phrases VALUES(NULL, 'mifam\'am', 'I understand');
INSERT INTO phrases VALUES(NULL, 'Farsi mifam\'am', 'I understand Persian');
INSERT INTO phrases VALUES(NULL, 'Kami Farsi mifam\'am', 'I understand a bit of Persian');
INSERT INTO phrases VALUES(NULL, 'To Farsi mifam\'i?', 'Do you understand Persian?');
INSERT INTO phrases VALUES(NULL, 'Farsi nemifam\'am', 'I don\'t understand Persian');
INSERT INTO phrases VALUES(NULL, 'bebakhshid', 'Excuse me/sorry');
INSERT INTO phrases VALUES(NULL, 'Daar\'am Farsi yaad migiram', 'I\'m currently learning Persian');
INSERT INTO phrases VALUES(NULL, 'lotfan', 'please');
INSERT INTO phrases VALUES(NULL, 'yavoshtar', 'slower');
INSERT INTO phrases VALUES(NULL, 'Lotfan yavoshtar sohbat kon', 'Please speak slower');
INSERT INTO phrases VALUES(NULL, 'mishe', 'is it possible');
INSERT INTO phrases VALUES(NULL, 'Mishe yavoshtar sohbat kon\'i?', 'Could you speak slower?');
INSERT INTO phrases VALUES(NULL, 'Yavoshtar lotfan', 'Slower please');
INSERT INTO phrases VALUES(NULL, 'tekraar', 'repeat');
INSERT INTO phrases VALUES(NULL, 'Mishe tekrar kon\'i?', 'Could you repeat?');
INSERT INTO phrases VALUES(NULL, 'sefr', 'zero');
INSERT INTO phrases VALUES(NULL, 'yek', 'one');
INSERT INTO phrases VALUES(NULL, 'do', 'two');
INSERT INTO phrases VALUES(NULL, 'se', 'three');
INSERT INTO phrases VALUES(NULL, 'chahar', 'four');
INSERT INTO phrases VALUES(NULL, 'panj', 'five');
INSERT INTO phrases VALUES(NULL, 'shish', 'six');
INSERT INTO phrases VALUES(NULL, 'haft', 'seven');
INSERT INTO phrases VALUES(NULL, 'hasht', 'eight');
INSERT INTO phrases VALUES(NULL, 'noh', 'nine');
INSERT INTO phrases VALUES(NULL, 'dah', 'ten');
INSERT INTO phrases VALUES(NULL, 'yozda', 'eleven');
INSERT INTO phrases VALUES(NULL, 'davaazda', 'twelve');
INSERT INTO phrases VALUES(NULL, 'sizda', 'thirteen');
INSERT INTO phrases VALUES(NULL, 'chaharda', 'fourteen');
INSERT INTO phrases VALUES(NULL, 'poonsda', 'fifteen');
INSERT INTO phrases VALUES(NULL, 'shoonsda', 'sixteen');
INSERT INTO phrases VALUES(NULL, 'heevda', 'seventeen');
INSERT INTO phrases VALUES(NULL, 'heejda', 'eighteen');
INSERT INTO phrases VALUES(NULL, 'noozda', 'nineteen');
INSERT INTO phrases VALUES(NULL, 'bist', 'twenty');
INSERT INTO phrases VALUES(NULL, 'bist\'o yek', 'twenty-one');
INSERT INTO phrases VALUES(NULL, 'si', 'thirty');
INSERT INTO phrases VALUES(NULL, 'si\'o do', 'thirty-two');
INSERT INTO phrases VALUES(NULL, 'chehel', 'forty');
INSERT INTO phrases VALUES(NULL, 'chehel\'o se', 'forty-three');
INSERT INTO phrases VALUES(NULL, 'panja', 'fifty');
INSERT INTO phrases VALUES(NULL, 'shast', 'sixty');
INSERT INTO phrases VALUES(NULL, 'hafdaad', 'seventy');
INSERT INTO phrases VALUES(NULL, 'hashdaad', 'eighty');
INSERT INTO phrases VALUES(NULL, 'navad', 'ninety');
INSERT INTO phrases VALUES(NULL, 'sad', 'hundred');
INSERT INTO phrases VALUES(NULL, 'sad\'o panj', 'one hundred and five');
INSERT INTO phrases VALUES(NULL, 'sad\'o chehel\'o do', 'one hundred and forty two');
INSERT INTO phrases VALUES(NULL, 'divist', 'two hundred');
INSERT INTO phrases VALUES(NULL, 'divist\'o panja', 'two hundred and fifty');
INSERT INTO phrases VALUES(NULL, 'sisad', 'three hundred');
INSERT INTO phrases VALUES(NULL, 'chaharsad', 'four hundred');
INSERT INTO phrases VALUES(NULL, 'poonsad', 'five hundred');
INSERT INTO phrases VALUES(NULL, 'shishsad', 'six hundred');
INSERT INTO phrases VALUES(NULL, 'haftsad', 'seven hundred');
INSERT INTO phrases VALUES(NULL, 'hashtsad', 'eight hundred');
INSERT INTO phrases VALUES(NULL, 'nosad', 'nine hundred');
INSERT INTO phrases VALUES(NULL, 'hezar', 'thousand');
INSERT INTO phrases VALUES(NULL, 'hafte', 'week');
INSERT INTO phrases VALUES(NULL, 'shanbe', 'Saturday');
INSERT INTO phrases VALUES(NULL, 'yekshanbe', 'Sunday');
INSERT INTO phrases VALUES(NULL, 'doshanbe', 'Monday');
INSERT INTO phrases VALUES(NULL, 'seshanbe', 'Tuesday');
INSERT INTO phrases VALUES(NULL, 'chaharshanbe', 'Wednesday');
INSERT INTO phrases VALUES(NULL, 'panjshanbe', 'Thursday');
INSERT INTO phrases VALUES(NULL, 'jome', 'Friday');
INSERT INTO phrases VALUES(NULL, 'jome tatille', 'Friday(holiday)');
INSERT INTO phrases VALUES(NULL, 'hamseir', 'spouse');
INSERT INTO phrases VALUES(NULL, 'Be Farsi chi mishe?', 'What is it in Persian?');
INSERT INTO phrases VALUES(NULL, '\'Camera\' be Farsi chi mishe?', 'What is a camera called in Persian?');
INSERT INTO phrases VALUES(NULL, 'durbeen', 'camera');
INSERT INTO phrases VALUES(NULL, 'janvier', 'January');
INSERT INTO phrases VALUES(NULL, 'fevrier', 'February');
INSERT INTO phrases VALUES(NULL, 'mars', 'March');
INSERT INTO phrases VALUES(NULL, 'avril', 'April');
INSERT INTO phrases VALUES(NULL, 'mei', 'May');
INSERT INTO phrases VALUES(NULL, 'juin', 'June');
INSERT INTO phrases VALUES(NULL, 'juillet', 'July');
INSERT INTO phrases VALUES(NULL, 'aout', 'August');
INSERT INTO phrases VALUES(NULL, 'septembre', 'September');
INSERT INTO phrases VALUES(NULL, 'octobre', 'October');
INSERT INTO phrases VALUES(NULL, 'novembre', 'November');
INSERT INTO phrases VALUES(NULL, 'decembre', 'December');
INSERT INTO phrases VALUES(NULL, 'bahar', 'spring');
INSERT INTO phrases VALUES(NULL, 'taabestoon', 'summer');
INSERT INTO phrases VALUES(NULL, 'pais', 'fall');
INSERT INTO phrases VALUES(NULL, 'zemestoon', 'winter');
INSERT INTO phrases VALUES(NULL, 'aval', 'first');
INSERT INTO phrases VALUES(NULL, 'aval\'e juillet', 'first of July');
INSERT INTO phrases VALUES(NULL, 'dovom', 'second (2nd)');
INSERT INTO phrases VALUES(NULL, 'sevom', 'third');
INSERT INTO phrases VALUES(NULL, 'chaharom', 'fourth');
INSERT INTO phrases VALUES(NULL, 'panjom', 'fifth');
INSERT INTO phrases VALUES(NULL, 'bist\'o hashtom', 'twenty-eighth');
INSERT INTO phrases VALUES(NULL, 'Emrooz bist\'o hashtome janvier hast', 'Today is the 28th of January');
INSERT INTO phrases VALUES(NULL, 'Haser\'i?', 'Are you ready?');
INSERT INTO phrases VALUES(NULL, 'Haser\'am', 'I am ready');
INSERT INTO phrases VALUES(NULL, 'Chai mikhor\'i?', 'Would you drink some tea?');
INSERT INTO phrases VALUES(NULL, 'Bale, chai mikhor\'am', 'Yes, I will drink some tea');
INSERT INTO phrases VALUES(NULL, 'Chai ba sheekar', 'Tea with sugar');
INSERT INTO phrases VALUES(NULL, 'Chai ba ghand', 'Tea with sugar cubes');
INSERT INTO phrases VALUES(NULL, 'Chai ba shirini', 'Tea with sweets');
INSERT INTO phrases VALUES(NULL, 'Na mersi', 'No thank you');
INSERT INTO phrases VALUES(NULL, 'Chai mikham', 'I want tea');
INSERT INTO phrases VALUES(NULL, 'Chai nemikham', 'I don\'t want tea');
INSERT INTO phrases VALUES(NULL, 'Chai nemikhoram', 'I won\'t drink any tea');
INSERT INTO phrases VALUES(NULL, 'Bishtar (baazam) chai mikhai?', 'Do you want more tea?');
INSERT INTO phrases VALUES(NULL, 'ghave', 'coffee');
INSERT INTO phrases VALUES(NULL, 'ghave\'ye torkey', 'type of coffee');
INSERT INTO phrases VALUES(NULL, 'shir', 'milk (also means lion)');
INSERT INTO phrases VALUES(NULL, 'chai ba shir', 'tea with milk');
INSERT INTO phrases VALUES(NULL, 'aab', 'water');
INSERT INTO phrases VALUES(NULL, 'aab ba yakh', 'water with ice');
INSERT INTO phrases VALUES(NULL, 'aab bedune yakh', 'water with out ice');
INSERT INTO phrases VALUES(NULL, 'sheirbat', 'special fruity drink');
INSERT INTO phrases VALUES(NULL, 'aab mive', 'fruit juice');
INSERT INTO phrases VALUES(NULL, 'nooshaabe', 'soft drink');
INSERT INTO phrases VALUES(NULL, 'aab jo', 'beer');
INSERT INTO phrases VALUES(NULL, 'sharaab', 'wine');
INSERT INTO phrases VALUES(NULL, 'sharaab\'e ghermez', 'red wine');
INSERT INTO phrases VALUES(NULL, 'sharaab\'e sefid', 'white wine');
INSERT INTO phrases VALUES(NULL, 'be salomatti', 'cheers (to your health)');
INSERT INTO phrases VALUES(NULL, 'chi mail mikhoni?', 'What would you like? (Literal: What do you wish for?)');
INSERT INTO phrases VALUES(NULL, 'To chi mikhori?', 'What would you like to eat?');
INSERT INTO phrases VALUES(NULL, 'baashe', 'okay');
INSERT INTO phrases VALUES(NULL, 'khune', 'home');
INSERT INTO phrases VALUES(NULL, 'khune\'ye man', 'my house');
INSERT INTO phrases VALUES(NULL, 'khune\'ye ma', 'our house');
INSERT INTO phrases VALUES(NULL, 'khune\'ye oonha', 'their house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye kie?', 'Whose house is this?');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye man\'e', 'It\'s my house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye to\'st (to\'e)', 'It\'s your house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye oonha\'st', 'It\'s their house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye shoma\'st', 'It\'s your house (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye ma\'st', 'It\'s our house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye ishun\'e', 'It\'s his/her house (if person is present)');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye ou\'st (oune)', 'It\'s his/her house (if person is not present)');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye madeir\'e man\'e', 'It\'s my mother\'s house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye pedar\'e to\'st', 'It\'s your father\'s house');
INSERT INTO phrases VALUES(NULL, 'In khune\'ye Matt\'e', 'It\'s Matt\'s house');
INSERT INTO phrases VALUES(NULL, 'Fek mikhonam', 'I think');
INSERT INTO phrases VALUES(NULL, 'ghave khune', 'coffee shop');
INSERT INTO phrases VALUES(NULL, 'cinama', 'movie theatre');
INSERT INTO phrases VALUES(NULL, 'muse', 'museum');
INSERT INTO phrases VALUES(NULL, 'bonk', 'bank');
INSERT INTO phrases VALUES(NULL, 'baazaar (paasaj)', 'shopping center');
INSERT INTO phrases VALUES(NULL, 'vasate shahr (markaze shahr)', 'city center');
INSERT INTO phrases VALUES(NULL, 'shahr', 'city');
INSERT INTO phrases VALUES(NULL, 'estakhr', 'pool');
INSERT INTO phrases VALUES(NULL, 'masjed', 'mosque');
INSERT INTO phrases VALUES(NULL, 'keleesa', 'church');
INSERT INTO phrases VALUES(NULL, 'keneese', 'synagogue');
INSERT INTO phrases VALUES(NULL, 'Shoma as koja hastid?', 'Where are you from? (super-formal)');
INSERT INTO phrases VALUES(NULL, 'Koja zendeghi mikhonid?', 'Where do you live? (super-formal)');
INSERT INTO phrases VALUES(NULL, 'mamnoonam', 'I am thankful');
INSERT INTO phrases VALUES(NULL, 'befarma (formal: befarma\'in)', 'help yourself (invitation)');
INSERT INTO phrases VALUES(NULL, 'Befarma beshin', 'Please sit');
INSERT INTO phrases VALUES(NULL, 'Befarma khunam', 'Please come to my house');
INSERT INTO phrases VALUES(NULL, 'Gorosne\'i?', 'Are you hungry?');
INSERT INTO phrases VALUES(NULL, 'Gorosnam\'e', 'I am hungry');
INSERT INTO phrases VALUES(NULL, 'Gorosne nistam (goshne)', 'I\'m not hungry');
INSERT INTO phrases VALUES(NULL, 'ghaza', 'food');
INSERT INTO phrases VALUES(NULL, 'Na, taaze khord\'am', 'No, I just ate');
INSERT INTO phrases VALUES(NULL, 'Teshne\'i?', 'Are you thirsty?');
INSERT INTO phrases VALUES(NULL, 'sobhune', 'breakfast');
INSERT INTO phrases VALUES(NULL, 'naahar', 'lunch');
INSERT INTO phrases VALUES(NULL, 'shaam', 'supper');
INSERT INTO phrases VALUES(NULL, 'asrune', 'meal between lunch and supper (lupper)');
INSERT INTO phrases VALUES(NULL, 'khosh aamadi', 'welcome');
INSERT INTO phrases VALUES(NULL, 'Befarma shaam', 'Help yourself to dinner');
INSERT INTO phrases VALUES(NULL, 'Befarma naahar', 'Help yourself to lunch');
INSERT INTO phrases VALUES(NULL, 'Naahar hasere', 'Lunch is ready');
INSERT INTO phrases VALUES(NULL, 'nuno panir', 'bread and cheese');
INSERT INTO phrases VALUES(NULL, 'asal', 'honey');
INSERT INTO phrases VALUES(NULL, 'moraba', 'jam');
INSERT INTO phrases VALUES(NULL, 'geirdu', 'walnuts');
INSERT INTO phrases VALUES(NULL, 'pollo', 'cooked rice');
INSERT INTO phrases VALUES(NULL, 'berenj', 'uncooked rice');
INSERT INTO phrases VALUES(NULL, 'khoresh', 'stew');
INSERT INTO phrases VALUES(NULL, 'sabzi', 'green vegetables');
INSERT INTO phrases VALUES(NULL, 'maast', 'yogurt');
INSERT INTO phrases VALUES(NULL, 'namak', 'salt');
INSERT INTO phrases VALUES(NULL, 'felfel', 'pepper');
INSERT INTO phrases VALUES(NULL, 'deser', 'dessert');
INSERT INTO phrases VALUES(NULL, 'pazirai', 'hosting');
INSERT INTO phrases VALUES(NULL, 'Daste tun dard nakone', 'Hope your hand doesn\'t hurt (way to say thanks) (formal)');
INSERT INTO phrases VALUES(NULL, 'Dastet dard nakone', 'Hope your hand doesn\'t hurt (way to say thanks)');
INSERT INTO phrases VALUES(NULL, 'Mamnoon as pazirai tun', 'Thanks for hosting');
INSERT INTO phrases VALUES(NULL, 'Baayad yavosh yavosh beram', 'I will slowly start leaving');
INSERT INTO phrases VALUES(NULL, 'beram', 'to leave');
INSERT INTO phrases VALUES(NULL, 'yavosh', 'slowly');
INSERT INTO phrases VALUES(NULL, 'Baayad yavosh yavosh berim', 'We will slowly start leaving');
INSERT INTO phrases VALUES(NULL, 'Kheili khosh gozasht', 'A great time was had');
INSERT INTO phrases VALUES(NULL, 'Naahar kheili aali bud', 'Lunch was really great');
INSERT INTO phrases VALUES(NULL, 'Khahesh mikhonam', 'You\'re welcome');
INSERT INTO phrases VALUES(NULL, 'Na, bemmon baraa\'ye shaam', 'No, stay for dinner');
INSERT INTO phrases VALUES(NULL, 'morgh', 'chicken');
INSERT INTO phrases VALUES(NULL, 'rang', 'color');
INSERT INTO phrases VALUES(NULL, 'rang\'ha', 'colors');
INSERT INTO phrases VALUES(NULL, 'siah', 'black');
INSERT INTO phrases VALUES(NULL, 'sefid', 'white');
INSERT INTO phrases VALUES(NULL, 'banafsh', 'purple');
INSERT INTO phrases VALUES(NULL, 'aabi', 'blue');
INSERT INTO phrases VALUES(NULL, 'sabz', 'green');
INSERT INTO phrases VALUES(NULL, 'zard', 'yellow');
INSERT INTO phrases VALUES(NULL, 'naarenji', 'orange');
INSERT INTO phrases VALUES(NULL, 'sorkh/gheirmez', 'red');
INSERT INTO phrases VALUES(NULL, 'ghavei', 'brown');
INSERT INTO phrases VALUES(NULL, 'In morgh sefid\'e', 'This chicken is white');
INSERT INTO phrases VALUES(NULL, 'morgh\'e sefid', 'white chicken');
INSERT INTO phrases VALUES(NULL, 'In morgh\'ha siah\'han', 'These chickens are black');
INSERT INTO phrases VALUES(NULL, 'morgh\'ha\'ye siah', 'black chickens');
INSERT INTO phrases VALUES(NULL, 'Man se khaheir daar\'am', 'I have three sisters');
INSERT INTO phrases VALUES(NULL, 'Man se morgh\'e siah daar\'am', 'I have three black chickens');
INSERT INTO phrases VALUES(NULL, 'Man ye morgh\'e sefid daar\'am', 'I have a white chicken');
INSERT INTO phrases VALUES(NULL, 'koochik', 'small');
INSERT INTO phrases VALUES(NULL, 'In morgh koochik\'e', 'This chicken is small');
INSERT INTO phrases VALUES(NULL, 'In morgh\'ha koochik\'an', 'These chickens are small');
INSERT INTO phrases VALUES(NULL, 'In morgh koochik\'e vali in morgh koochik\'tare', 'This chicken is small but this chicken is smaller');
INSERT INTO phrases VALUES(NULL, 'In koochik\'tarin morgh\'e', 'This is the smallest chicken');
INSERT INTO phrases VALUES(NULL, 'bozorg, bozorgtar, bozorgtarin', 'big, bigger, biggest');
INSERT INTO phrases VALUES(NULL, 'feirz, feirztar, feirztarin (sari)', 'quick, quicker, quickest');
INSERT INTO phrases VALUES(NULL, 'kond, kondtar, kondtarin', 'slow, slower, slowest');
INSERT INTO phrases VALUES(NULL, 'ghashang, ghashang\'tar, ghashang\'tarin', 'nice looking, better looking, best looking');
INSERT INTO phrases VALUES(NULL, 'zesht, zeshtar, zeshtarin', 'ugly, uglier, ugliest');
INSERT INTO phrases VALUES(NULL, 'In morgh\'e siah ghashang\'e', 'This black chicken is nice looking');
INSERT INTO phrases VALUES(NULL, 'In morgh\'e sorkh kond\'e', 'This red chicken is slow');
INSERT INTO phrases VALUES(NULL, 'Vali un morgh\'e zard kondtar\'e', 'But that yellow chicken is slower');
INSERT INTO phrases VALUES(NULL, 'maasheen', 'car');
INSERT INTO phrases VALUES(NULL, 'maasheen\'ha', 'cars');
INSERT INTO phrases VALUES(NULL, 'khub, betar, betarin', 'good, better, best');
INSERT INTO phrases VALUES(NULL, 'gerun, geruntar, geruntarin', 'expensive, more expensive, most expensive');
INSERT INTO phrases VALUES(NULL, 'arzun, arzuntar, arzuntarin', 'cheap, cheaper, cheapest');
INSERT INTO phrases VALUES(NULL, 'saa\'at', 'clock/watch/time');
INSERT INTO phrases VALUES(NULL, 'chand', 'how much');
INSERT INTO phrases VALUES(NULL, 'Saa\'at chand\'e?', 'What time is it?');
INSERT INTO phrases VALUES(NULL, 'Saa\'at yek\'e', 'It\'s one o\'clock');
INSERT INTO phrases VALUES(NULL, 'Saa\'at do\'e', 'It\'s two o\'clock');
INSERT INTO phrases VALUES(NULL, 'Saa\'at se\'e', 'It\'s three o\'clock');
INSERT INTO phrases VALUES(NULL, 'Saa\'at davozdah\'e', 'It\'s twelve o\'clock');
INSERT INTO phrases VALUES(NULL, 'neem', 'half');
INSERT INTO phrases VALUES(NULL, 'Saa\'at sheesh\'o neem\'e', 'It\'s half past six (6:30)');
INSERT INTO phrases VALUES(NULL, 'rob', 'quarter');
INSERT INTO phrases VALUES(NULL, 'Saa\'at yek\'o rob\'e', 'It\'s quarter after one (1:15)');
INSERT INTO phrases VALUES(NULL, 'Saa\'at ye rob be yek\'e', 'It\'s quarter to one (12:45)');
INSERT INTO phrases VALUES(NULL, 'daghighei (min)', 'minute');
INSERT INTO phrases VALUES(NULL, 'Saa\'at dah\'o dah daghigh\'ast', 'It\'s ten ten (10:10)');
INSERT INTO phrases VALUES(NULL, 'Saa\'at dah daghighei be dah\'e', 'It\'s ten to ten (9:50)');
INSERT INTO phrases VALUES(NULL, 'Saa\'at no\'o panja daghigh\'ast', 'It\'s nine fifty (9:50)');
INSERT INTO phrases VALUES(NULL, 'hava', 'weather');
INSERT INTO phrases VALUES(NULL, 'Hava chetor\'e?', 'How is the weather?');
INSERT INTO phrases VALUES(NULL, 'Hava bad nist', 'The weather is not bad');
INSERT INTO phrases VALUES(NULL, 'Hava khub\'e', 'The weather is good');
INSERT INTO phrases VALUES(NULL, 'Hava bad\'e', 'The weather is bad');
INSERT INTO phrases VALUES(NULL, 'garm', 'warm');
INSERT INTO phrases VALUES(NULL, 'sard', 'cold');
INSERT INTO phrases VALUES(NULL, 'Hava sard\'e', 'The weather\'s cold');
INSERT INTO phrases VALUES(NULL, 'aaftaab', 'sun');
INSERT INTO phrases VALUES(NULL, 'Hava aaftaabi\'e', 'The weather\'s sunny');
INSERT INTO phrases VALUES(NULL, 'baarun', 'rain');
INSERT INTO phrases VALUES(NULL, 'Hava baaruni\'e', 'The weather\'s rainy');
INSERT INTO phrases VALUES(NULL, 'Hava martub\'e', 'The weather\'s humid');
INSERT INTO phrases VALUES(NULL, 'abr', 'cloud');
INSERT INTO phrases VALUES(NULL, 'Hava abri\'e', 'The weather\'s cloudy');
INSERT INTO phrases VALUES(NULL, 'Hava kami sard\'e', 'It\'s a little cold');
INSERT INTO phrases VALUES(NULL, 'Hava kheili garm\'e', 'It\'s really hot');
INSERT INTO phrases VALUES(NULL, 'Baad miaad', 'It\'s windy');
INSERT INTO phrases VALUES(NULL, 'khoshk', 'dry');
INSERT INTO phrases VALUES(NULL, 'Hava khoshk\'e', 'The weather is dry');
INSERT INTO phrases VALUES(NULL, 'Hava garm o martub\'e', 'The weather is hot and humid');
INSERT INTO phrases VALUES(NULL, 'Cheghadre?', 'How much?');
INSERT INTO phrases VALUES(NULL, 'Cheghadre hava khub\'e', 'The weather is really great (How much the weather is great)');
INSERT INTO phrases VALUES(NULL, 'Che hava\'ye khub\'ie', 'The weather is really great (How much the weather is great [short-form])');
INSERT INTO phrases VALUES(NULL, 'Baaroon miaad', 'It\'s raining');
INSERT INTO phrases VALUES(NULL, 'Daare baaroon miaad', 'It\'s currently raining');
INSERT INTO phrases VALUES(NULL, 'barf', 'snow');
INSERT INTO phrases VALUES(NULL, 'Barf miaad', 'It\'s snowing');
INSERT INTO phrases VALUES(NULL, 'allon', 'right now');
INSERT INTO phrases VALUES(NULL, 'eshgh', 'love');
INSERT INTO phrases VALUES(NULL, 'doosti', 'friendship');
INSERT INTO phrases VALUES(NULL, 'To eshgh\'e man\'i', 'You are my love');
INSERT INTO phrases VALUES(NULL, 'asheghetam', 'I\'m in love with you');
INSERT INTO phrases VALUES(NULL, 'dooset daar\'am', 'I like you');
INSERT INTO phrases VALUES(NULL, 'doost', 'friend');
INSERT INTO phrases VALUES(NULL, 'Doos\'am daar\'i?', 'Do you love me?');
INSERT INTO phrases VALUES(NULL, 'Manam dooset daar\'am', 'I love you too');
INSERT INTO phrases VALUES(NULL, 'jon/joon', 'dear');
INSERT INTO phrases VALUES(NULL, 'azizam', 'my dear');
INSERT INTO phrases VALUES(NULL, 'Azizam\'i', 'You are my dear');
INSERT INTO phrases VALUES(NULL, 'jigar', 'liver (sweet word to call someone)');
INSERT INTO phrases VALUES(NULL, 'ghorbunet beram', 'I hope I become a sacrifice for you');
INSERT INTO phrases VALUES(NULL, 'Kheili ziba\'i', 'You are very beautiful');
INSERT INTO phrases VALUES(NULL, 'Kheili khoshgel\'i', 'You are very pretty');
INSERT INTO phrases VALUES(NULL, 'Che khoshgel\'i', 'How pretty you are');
INSERT INTO phrases VALUES(NULL, 'boos bed\'e', 'give me a kiss');
INSERT INTO phrases VALUES(NULL, 'man mojarad\'am', 'I\'m single');
INSERT INTO phrases VALUES(NULL, 'man zan daar\'am', 'I have a wife');
INSERT INTO phrases VALUES(NULL, 'man shoheir daar\'am', 'I have a husband');
INSERT INTO phrases VALUES(NULL, 'man doost-dokhtar daar\'am', 'I have a girlfriend');
INSERT INTO phrases VALUES(NULL, 'man doost-pesar daar\'am', 'I have a boyfriend');
INSERT INTO phrases VALUES(NULL, 'man naamzad daar\'am', 'I have a fiance');
INSERT INTO phrases VALUES(NULL, 'vaalaa', 'truthfully');
INSERT INTO phrases VALUES(NULL, 'jaaye Ladan khaali\'e', 'Ladan is missed');
INSERT INTO phrases VALUES(NULL, 'Emrooz che roozi\'e?', 'What day is it?');
INSERT INTO phrases VALUES(NULL, 'maa', 'month');
INSERT INTO phrases VALUES(NULL, 'fasle', 'season');
INSERT INTO phrases VALUES(NULL, 'man hast\'am', 'I am');
INSERT INTO phrases VALUES(NULL, 'to hast\'i', 'you are');
INSERT INTO phrases VALUES(NULL, 'ou hast', 'he/she is');
INSERT INTO phrases VALUES(NULL, 'ma hast\'im', 'we are');
INSERT INTO phrases VALUES(NULL, 'shoma hast\'in', 'you are (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'unha hast\'an', 'they are');
INSERT INTO phrases VALUES(NULL, 'Man khub\'am', 'I\'m well');
INSERT INTO phrases VALUES(NULL, 'To khub\'i', 'You are well');
INSERT INTO phrases VALUES(NULL, 'Ou khub\'e', 'He/she is well');
INSERT INTO phrases VALUES(NULL, 'Ma khub\'im', 'We are well');
INSERT INTO phrases VALUES(NULL, 'Shoma khub\'in', 'You are well (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'Unha khub\'an', 'They are well');
INSERT INTO phrases VALUES(NULL, 'aazaad', 'free');
INSERT INTO phrases VALUES(NULL, 'deltang', 'tight-hearted (depressed, sad)');
INSERT INTO phrases VALUES(NULL, 'man nist\'am', 'I am not');
INSERT INTO phrases VALUES(NULL, 'to nist\'i', 'you are not');
INSERT INTO phrases VALUES(NULL, 'ou nist', 'he/she is not');
INSERT INTO phrases VALUES(NULL, 'ma nist\'im', 'we are not');
INSERT INTO phrases VALUES(NULL, 'shoma nist\'in', 'you are not (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'unha nist\'an', 'they are not');
INSERT INTO phrases VALUES(NULL, 'Man khoshhall nist\'am', 'I am not happy');
INSERT INTO phrases VALUES(NULL, 'Ma bad nist\'im', 'We are not bad');
INSERT INTO phrases VALUES(NULL, 'Unha bad nist\'an', 'They are not bad');
INSERT INTO phrases VALUES(NULL, 'budan', 'to be (infinitive)');
INSERT INTO phrases VALUES(NULL, 'daashtan', 'to have (infinitive)');
INSERT INTO phrases VALUES(NULL, 'bud', 'was');
INSERT INTO phrases VALUES(NULL, 'daasht', 'had');
INSERT INTO phrases VALUES(NULL, 'man nooshaabe daar\'am', 'I have pop');
INSERT INTO phrases VALUES(NULL, 'to daar\'i', 'you have');
INSERT INTO phrases VALUES(NULL, 'ou daar\'e', 'he/she has');
INSERT INTO phrases VALUES(NULL, 'ma daar\'im', 'we have');
INSERT INTO phrases VALUES(NULL, 'shoma daar\'in', 'you have (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'unha daar\'an', 'they have');
INSERT INTO phrases VALUES(NULL, 'kola', 'hat');
INSERT INTO phrases VALUES(NULL, 'Man kola daar\'am', 'I have a hat');
INSERT INTO phrases VALUES(NULL, 'To kola daar\'i', 'You have a hat');
INSERT INTO phrases VALUES(NULL, 'Ou kola daar\'e', 'He/she has a hat');
INSERT INTO phrases VALUES(NULL, 'Ma kola daar\'im', 'We have a hat');
INSERT INTO phrases VALUES(NULL, 'Shoma kola daar\'in', 'You have a hat (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'Unha kola daar\'an', 'They have a hat');
INSERT INTO phrases VALUES(NULL, 'Man kola na\'daar\'am', 'I don\'t have a hat');
INSERT INTO phrases VALUES(NULL, 'To ghaza na\'daar\'i', 'You don\'t have food');
INSERT INTO phrases VALUES(NULL, 'Ou aab jo na\'daar\'e', 'He/she doesn\'t have beer');
INSERT INTO phrases VALUES(NULL, 'Ma sharaab na\'daar\'im', 'We don\'t have wine');
INSERT INTO phrases VALUES(NULL, 'Shoma kola na\'daar\'in', 'You don\'t have a hat (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'Unha maasheen na\'daar\'an', 'They don\'t have a car');
INSERT INTO phrases VALUES(NULL, 'To chand saal daar\'i?', 'How old are you? (how many years do you have?)');
INSERT INTO phrases VALUES(NULL, 'Man bist o no saal daar\'am', 'I\'m twenty nine (I have 29 years)');
INSERT INTO phrases VALUES(NULL, 'Compyuteir daar\'am', 'I have a computer');
INSERT INTO phrases VALUES(NULL, 'Sara khune daar\'e', 'Sara has a house');
INSERT INTO phrases VALUES(NULL, 'Ou dah saal daar\'e', 'He/she is ten (he/she has ten years)');
INSERT INTO phrases VALUES(NULL, 'Ma podcast daar\'im', 'We have a podcast');
INSERT INTO phrases VALUES(NULL, 'Maasheen daar\'i?', 'Do you have a car?');
INSERT INTO phrases VALUES(NULL, 'Chand taa maasheen daar\'i?', 'How many cars do you have?');
INSERT INTO phrases VALUES(NULL, 'Man panj masheen daar\'am', 'I have five cars');
INSERT INTO phrases VALUES(NULL, 'Man panj taa masheen daar\'am', 'I have five [units] of cars');
INSERT INTO phrases VALUES(NULL, 'docharkhe', 'bicycle');
INSERT INTO phrases VALUES(NULL, 'mehmuni', 'party');
INSERT INTO phrases VALUES(NULL, 'Mehmuni chetor bud?', 'How was the party?');
INSERT INTO phrases VALUES(NULL, 'Khub bud', 'It was good');
INSERT INTO phrases VALUES(NULL, 'Khub na\'bud', 'It was not good');
INSERT INTO phrases VALUES(NULL, 'Khaste bud\'am', 'I was tired');
INSERT INTO phrases VALUES(NULL, 'Ma khoshhall bud\'im', 'We were happy');
INSERT INTO phrases VALUES(NULL, 'Unha deltang bud\'an', 'They were heavy-hearted');
INSERT INTO phrases VALUES(NULL, 'baro\'ye inke', 'because (for the reason that)');
INSERT INTO phrases VALUES(NULL, 'Mehmuni khub na\'bud baro\'ye inke khaste bud\'am', 'The party was not good because I was tired');
INSERT INTO phrases VALUES(NULL, 'Mehmuni bad na\'bud vali khaste bud\'am', 'The party wasn\'t bad but I was tired');
INSERT INTO phrases VALUES(NULL, 'Akheire hafte chi kar keird\'i?', 'What did you do this weekend?');
INSERT INTO phrases VALUES(NULL, 'akheir', 'end');
INSERT INTO phrases VALUES(NULL, 'akheire hafte', 'weekend');
INSERT INTO phrases VALUES(NULL, 'keird\'i', 'you did');
INSERT INTO phrases VALUES(NULL, 'chi kar', 'what work/activities');
INSERT INTO phrases VALUES(NULL, 'keirdan', 'to do (infinitive)');
INSERT INTO phrases VALUES(NULL, 'keird', 'did');
INSERT INTO phrases VALUES(NULL, 'raftan', 'to go (infinitive)');
INSERT INTO phrases VALUES(NULL, 'raft', 'went');
INSERT INTO phrases VALUES(NULL, 'Raft\'am cinama', 'I went to the theatre');
INSERT INTO phrases VALUES(NULL, 'be', 'to');
INSERT INTO phrases VALUES(NULL, 'Raft\'am kelaase nagoshi', 'I went to a drawing class');
INSERT INTO phrases VALUES(NULL, 'to raft\'i', 'you went');
INSERT INTO phrases VALUES(NULL, 'unha raft\'an', 'they went');
INSERT INTO phrases VALUES(NULL, 'Man keird\'am', 'I did');
INSERT INTO phrases VALUES(NULL, 'Ma keird\'im', 'We did');
INSERT INTO phrases VALUES(NULL, 'Akheire hafte chi kar keird\'in?', 'What did you guys do this weekend?');
INSERT INTO phrases VALUES(NULL, 'Raft\'im muse', 'We went to the musem');
INSERT INTO phrases VALUES(NULL, 'Jome shab raft\'am muse', 'Friday night I went to the museum');
INSERT INTO phrases VALUES(NULL, 'Shanbe raft\'im park', 'Saturday we went to the park');
INSERT INTO phrases VALUES(NULL, 'Na\'raft\'am', 'I didn\'t go');
INSERT INTO phrases VALUES(NULL, 'Na, na\'raft\'am park', 'No I didn\'t go to the park');
INSERT INTO phrases VALUES(NULL, 'Khosh gozasht?', 'Did you have a good time?');
INSERT INTO phrases VALUES(NULL, 'ezafe', 'linking word (Ex. the e in zan\'e man)');
INSERT INTO phrases VALUES(NULL, 'agha', 'Mr');
INSERT INTO phrases VALUES(NULL, 'Agha\'ye Davis', 'Mr Davis');
INSERT INTO phrases VALUES(NULL, 'Khanum', 'Mrs/Ms');
INSERT INTO phrases VALUES(NULL, 'Khanum\'e Azari', 'Mrs Azari');
INSERT INTO phrases VALUES(NULL, 'Leyla khanum', 'polite way to refer to woman (Leyla)');
INSERT INTO phrases VALUES(NULL, 'Matt agha', 'polite way to refer to man (Matt)');
INSERT INTO phrases VALUES(NULL, 'Film\'e Bambi', 'The movie Bambi');
INSERT INTO phrases VALUES(NULL, 'Khiabun', 'street');
INSERT INTO phrases VALUES(NULL, 'Khiabun\'e Maisonneuve', 'Maisonneuve St');
INSERT INTO phrases VALUES(NULL, 'ketaab\'e khub', 'good book');
INSERT INTO phrases VALUES(NULL, 'film\'e bad', 'bad movie');
INSERT INTO phrases VALUES(NULL, 'khosh-maze', 'delicious');
INSERT INTO phrases VALUES(NULL, 'bad-maze', 'bad tasting');
INSERT INTO phrases VALUES(NULL, 'ghaza\'ye khosh-maze', 'delicious food');
INSERT INTO phrases VALUES(NULL, 'ghaza\'ye bad-maze', 'bad-tasting food');
INSERT INTO phrases VALUES(NULL, 'rhaahat', 'comfortable');
INSERT INTO phrases VALUES(NULL, 'na\'rhaahat', 'uncomfortable');
INSERT INTO phrases VALUES(NULL, 'sandali', 'chair');
INSERT INTO phrases VALUES(NULL, 'sandali\'e rhaahat', 'comfortable chair');
INSERT INTO phrases VALUES(NULL, 'sandali\'e na\'rhaahat', 'uncomfortable chair');
INSERT INTO phrases VALUES(NULL, 'khiabun\'e kootah', 'short street');
INSERT INTO phrases VALUES(NULL, 'khiabun\'e boland', 'long street');
INSERT INTO phrases VALUES(NULL, 'chic', 'elegant');
INSERT INTO phrases VALUES(NULL, 'ghorbati', 'shabby');
INSERT INTO phrases VALUES(NULL, 'neiboss', 'clothes');
INSERT INTO phrases VALUES(NULL, 'neiboss\'e chic', 'nice clothes');
INSERT INTO phrases VALUES(NULL, 'neiboss\'e ghorbati', 'shabby clothes');
INSERT INTO phrases VALUES(NULL, 'taariq', 'dark');
INSERT INTO phrases VALUES(NULL, 'rhoshan', 'light/bright');
INSERT INTO phrases VALUES(NULL, 'shab\'e taariq', 'dark night');
INSERT INTO phrases VALUES(NULL, 'rooz\'e rhoshan', 'bright day');
INSERT INTO phrases VALUES(NULL, 'ketaab\'e boland\'e bozorg', 'big long book');
INSERT INTO phrases VALUES(NULL, 'Khanum\'e Azari\'ye ziba', 'beautiful Mrs Azari');
INSERT INTO phrases VALUES(NULL, 'barodar\'e baamaaze\'ye man', 'my funny brother');
INSERT INTO phrases VALUES(NULL, 'baamaaze', 'funny');
INSERT INTO phrases VALUES(NULL, 'shab\'e taariq\'e sard', 'cold dark night');
INSERT INTO phrases VALUES(NULL, 'ketaab\'am', 'my book (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'ketaab\'et', 'your book (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'ketaab\'esh', 'his/her book (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'ketaab\'emun', 'our book (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'ketaab\'etun', 'your book (plural/formal) (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'ketaab\'eshun', 'their book (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'maasheen\'e koochik\'e man', 'my small car');
INSERT INTO phrases VALUES(NULL, 'maasheen\'e koochik\'am', 'my small car (short form possessive)');
INSERT INTO phrases VALUES(NULL, 'maasheen\'e koochik\'e gerun\'e man', 'my small expensive car');
INSERT INTO phrases VALUES(NULL, 'maasheen\'e koochik\'e gerun\'am', 'my small expensive car (short-form possessive)');
INSERT INTO phrases VALUES(NULL, 'maal', 'property');
INSERT INTO phrases VALUES(NULL, 'maal\'e man', 'mine');
INSERT INTO phrases VALUES(NULL, 'maal\'e to', 'yours');
INSERT INTO phrases VALUES(NULL, 'Maal\'e kie?', 'Whose is this?');
INSERT INTO phrases VALUES(NULL, 'In maasheen maal\'e kie?', 'Whose car is this?');
INSERT INTO phrases VALUES(NULL, 'In maasheen maal\'e man\'e', 'This is my car');
INSERT INTO phrases VALUES(NULL, 'Un telephone maal\'e kie?', 'Whose phone is that?');
INSERT INTO phrases VALUES(NULL, 'kharaab', 'not working (broken/not-functional)');
INSERT INTO phrases VALUES(NULL, 'shodan', 'to become (infinitive)');
INSERT INTO phrases VALUES(NULL, 'telefon keirdan', 'make a phone call (do a phone call)');
INSERT INTO phrases VALUES(NULL, 'baazi keirdan', 'to play');
INSERT INTO phrases VALUES(NULL, 'aashpazi keirdan', 'to cook');
INSERT INTO phrases VALUES(NULL, 'kar keird\'am', 'I worked');
INSERT INTO phrases VALUES(NULL, 'Unha kar keird\'an', 'They worked');
INSERT INTO phrases VALUES(NULL, 'Ma kar keird\'im', 'We worked');
INSERT INTO phrases VALUES(NULL, 'baazi keird\'im', 'we played');
INSERT INTO phrases VALUES(NULL, 'Aashpazi keird\'i', 'You cooked');
INSERT INTO phrases VALUES(NULL, 'Telefon keird\'im', 'We phoned');
INSERT INTO phrases VALUES(NULL, 'Tambrin keird\'am', 'I practiced');
INSERT INTO phrases VALUES(NULL, 'Tamaasha keird\'am', 'I watched');
INSERT INTO phrases VALUES(NULL, 'Dorost keird\'am', 'I made');
INSERT INTO phrases VALUES(NULL, 'sandevich', 'sandwich');
INSERT INTO phrases VALUES(NULL, 'Sandevich dorost keird\'am', 'I made a sandwich');
INSERT INTO phrases VALUES(NULL, 'Film tamaasha keird\'am', 'I watched a movie');
INSERT INTO phrases VALUES(NULL, 'Piano tambrin keird\'am', 'I practiced piano');
INSERT INTO phrases VALUES(NULL, 'Emrooz kar keird\'am', 'I worked today');
INSERT INTO phrases VALUES(NULL, 'Dirooz kar keird\'am', 'I worked yesterday');
INSERT INTO phrases VALUES(NULL, 'shod', 'became');
INSERT INTO phrases VALUES(NULL, 'man shod\'am', 'I became');
INSERT INTO phrases VALUES(NULL, 'to shod\'i', 'you became');
INSERT INTO phrases VALUES(NULL, 'ma shod\'im', 'we became');
INSERT INTO phrases VALUES(NULL, 'ou shod', 'he/she became');
INSERT INTO phrases VALUES(NULL, 'shoma shod\'in', 'you became (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'unha shod\'an', 'they became');
INSERT INTO phrases VALUES(NULL, 'Khoshal shod\'am', 'I became happy (sometimes used during goodbye)');
INSERT INTO phrases VALUES(NULL, 'Na\'rhaahat shod\'am', 'I became upset (uncomfortable)');
INSERT INTO phrases VALUES(NULL, 'Asabaani shod\'am', 'I became angry');
INSERT INTO phrases VALUES(NULL, 'Khaste shod\'am', 'I became tired');
INSERT INTO phrases VALUES(NULL, 'Baaz shodan', 'to open (to become open)');
INSERT INTO phrases VALUES(NULL, 'Daar baaz shod', 'The door opened');
INSERT INTO phrases VALUES(NULL, 'Resturan baaz shod', 'The restaurant opened');
INSERT INTO phrases VALUES(NULL, 'Resturan baaz\'e', 'The restaurant is open');
INSERT INTO phrases VALUES(NULL, 'baste shodan', 'closed');
INSERT INTO phrases VALUES(NULL, 'Daar baste shod', 'The door closed');
INSERT INTO phrases VALUES(NULL, 'Maghaaze baste shod', 'The store closed');
INSERT INTO phrases VALUES(NULL, 'maghaaze', 'store');
INSERT INTO phrases VALUES(NULL, 'Haser shodan', 'To become ready');
INSERT INTO phrases VALUES(NULL, 'Ghaza haser shod', 'The food became ready');
INSERT INTO phrases VALUES(NULL, 'Haser shod\'am', 'I became ready');
INSERT INTO phrases VALUES(NULL, 'fekr keird', 'thought');
INSERT INTO phrases VALUES(NULL, 'Chi fekr keird?', 'What did he/she think?');
INSERT INTO phrases VALUES(NULL, 'rooye (roo)', 'on (on top)');
INSERT INTO phrases VALUES(NULL, 'zire', 'under');
INSERT INTO phrases VALUES(NULL, 'meez', 'table');
INSERT INTO phrases VALUES(NULL, 'Ketaab rooye meez\'e', 'The book is on the table');
INSERT INTO phrases VALUES(NULL, 'Telefon zire meez\'e', 'The phone is under (beneath) the table');
INSERT INTO phrases VALUES(NULL, 'tooye (too)', 'in (inside)');
INSERT INTO phrases VALUES(NULL, 'birune', 'outside of');
INSERT INTO phrases VALUES(NULL, 'Telefon tooye keef\'e', 'The phone is in the purse');
INSERT INTO phrases VALUES(NULL, 'keef', 'purse');
INSERT INTO phrases VALUES(NULL, 'Telefon birune keef\'e', 'The phone is outside of the purse');
INSERT INTO phrases VALUES(NULL, 'jeloye (jelo)', 'in front of');
INSERT INTO phrases VALUES(NULL, 'poshte', 'behind');
INSERT INTO phrases VALUES(NULL, 'Sandali jeloye meez\'e', 'The chair is in front of the table');
INSERT INTO phrases VALUES(NULL, 'Sandali poshte meez\'e', 'The chair is behind the table');
INSERT INTO phrases VALUES(NULL, 'Compyuteir rooye meez\'e', 'The computer is on the table');
INSERT INTO phrases VALUES(NULL, 'Telefon\'am rooye meez\'e', 'My phone is on the table');
INSERT INTO phrases VALUES(NULL, 'gaaraj', 'garage');
INSERT INTO phrases VALUES(NULL, 'Masheen tooye gaaraj\'e', 'The car is in the garage');
INSERT INTO phrases VALUES(NULL, 'balaaye', 'above');
INSERT INTO phrases VALUES(NULL, 'paayine', 'below');
INSERT INTO phrases VALUES(NULL, 'Parande balaaye derakht\'e', 'The bird is above the tree');
INSERT INTO phrases VALUES(NULL, 'parande', 'bird');
INSERT INTO phrases VALUES(NULL, 'derakht', 'tree');
INSERT INTO phrases VALUES(NULL, 'Sag paayine meez\'e', 'The dog is under the table');
INSERT INTO phrases VALUES(NULL, 'pahlooye (pahloo)', 'next to');
INSERT INTO phrases VALUES(NULL, 'Televizion pahlooye moble', 'The television is next to the couch');
INSERT INTO phrases VALUES(NULL, 'moble', 'couch');
INSERT INTO phrases VALUES(NULL, 'kenare', 'by (by the side of)');
INSERT INTO phrases VALUES(NULL, 'Telefon kenare moble', 'The phone is by the couch');
INSERT INTO phrases VALUES(NULL, 'dakheil', 'in (when describing self ex. I\'m in the store)');
INSERT INTO phrases VALUES(NULL, 'Dakheil\'e maghaaz\'am', 'I\'m in the store');
INSERT INTO phrases VALUES(NULL, 'tarafe chap\'e', 'to the left of');
INSERT INTO phrases VALUES(NULL, 'tarafe raast\'e', 'to the right of');
INSERT INTO phrases VALUES(NULL, 'Sara tarafe raast\'e Mariam\'e', 'Sara is to the right of Mariam');
INSERT INTO phrases VALUES(NULL, 'Dave tarafe chap\'e John\'e', 'Dave is to the left of John');
INSERT INTO phrases VALUES(NULL, 'rube ruye', 'opposite of');
INSERT INTO phrases VALUES(NULL, 'Masheen rube ruye khun\'ast', 'The car is opposite the house (in front of the house)');
INSERT INTO phrases VALUES(NULL, 'midun\'am', 'I know');
INSERT INTO phrases VALUES(NULL, 'dunestan', 'to know (infinitive)');
INSERT INTO phrases VALUES(NULL, 'dun', 'to know (present stem)');
INSERT INTO phrases VALUES(NULL, 'midun\'i', 'you know');
INSERT INTO phrases VALUES(NULL, 'midun\'e', 'he/she knows');
INSERT INTO phrases VALUES(NULL, 'ne\'midun\'am', 'I don\'t know');
INSERT INTO phrases VALUES(NULL, 'shastan', 'to sit (infinitive)');
INSERT INTO phrases VALUES(NULL, 'sheen', 'sit (present stem)');
INSERT INTO phrases VALUES(NULL, 'misheen\'am', 'I sit');
INSERT INTO phrases VALUES(NULL, 'misheen\'im', 'we sit');
INSERT INTO phrases VALUES(NULL, 'ne\'misheen\'an', 'They don\'t sit');
INSERT INTO phrases VALUES(NULL, 're', 'to go (present stem of raftan)');
INSERT INTO phrases VALUES(NULL, 'mir\'am', 'I go');
INSERT INTO phrases VALUES(NULL, 'mir\'in', 'you go (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'khordan', 'to eat (infinitive)');
INSERT INTO phrases VALUES(NULL, 'khord', 'ate');
INSERT INTO phrases VALUES(NULL, 'mikhor\'an', 'they eat');
INSERT INTO phrases VALUES(NULL, 'khon', 'to do (present stem of keirdan)');
INSERT INTO phrases VALUES(NULL, 'mikhon\'am', 'I do');
INSERT INTO phrases VALUES(NULL, 'Kar mikhon\'am', 'I work');
INSERT INTO phrases VALUES(NULL, 'Chi kar mikhon\'i?', 'What are you doing?');
INSERT INTO phrases VALUES(NULL, 'Akheire hafte, chi kar mikhon\'i?', 'What are you doing this weekend?');
INSERT INTO phrases VALUES(NULL, 'shena keirdan', 'to swim (infinitive)');
INSERT INTO phrases VALUES(NULL, 'shena mikhon\'am', 'I swim');
INSERT INTO phrases VALUES(NULL, 'tamaasha mikhon\'am', 'I watch');
INSERT INTO phrases VALUES(NULL, 'Film tamaasha mikhon\'am', 'I watch a movie');
INSERT INTO phrases VALUES(NULL, 'Sobhane mikhor\'am', 'I eat breakfast');
INSERT INTO phrases VALUES(NULL, 'Naahar mikhor\'am', 'I eat lunch');
INSERT INTO phrases VALUES(NULL, 'Shaam mikhor\'am', 'I eat dinner');
INSERT INTO phrases VALUES(NULL, 'Sobha, sobhane mikhor\'am', 'In the mornings, I eat breakfast');
INSERT INTO phrases VALUES(NULL, 'Shabha, shaam mikhor\'am', 'In the evenings, I eat dinner');
INSERT INTO phrases VALUES(NULL, 'Yekshanbeha, televizion tamaasha mikhon\'am', 'On Sundays, I watch television');
INSERT INTO phrases VALUES(NULL, 'Doshanbe shabha, UFC tamaasha mikhon\'am', 'On Monday evenings, I watch UFC');
INSERT INTO phrases VALUES(NULL, 'aamedan', 'to come (infinite)');
INSERT INTO phrases VALUES(NULL, 'aa', 'to come (present stem)');
INSERT INTO phrases VALUES(NULL, 'mi\'am', 'I come');
INSERT INTO phrases VALUES(NULL, 'mia\'i', 'you come');
INSERT INTO phrases VALUES(NULL, 'ou miaad', 'he/she comes');
INSERT INTO phrases VALUES(NULL, 'ma mia\'im', 'we come');
INSERT INTO phrases VALUES(NULL, 'shoma mia\'in', 'you come (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'unha mi\'an', 'they come');
INSERT INTO phrases VALUES(NULL, 'mir\'i', 'you go');
INSERT INTO phrases VALUES(NULL, 'Be kar mir\'am', 'I go to work');
INSERT INTO phrases VALUES(NULL, 'Be kar mir\'im', 'We go to work');
INSERT INTO phrases VALUES(NULL, 'heir rooz', 'every day');
INSERT INTO phrases VALUES(NULL, 'Heir rooz, be kar mir\'am', 'Every day, I go to work');
INSERT INTO phrases VALUES(NULL, 'heir hafte', 'every week');
INSERT INTO phrases VALUES(NULL, 'Heir hafte, be kelaas\'e yoga mir\'am', 'Every week, I go to yoga class');
INSERT INTO phrases VALUES(NULL, 'heir maa', 'every month');
INSERT INTO phrases VALUES(NULL, 'Heir maa, be khune\'ye madeir zan\'am mir\'am', 'Every month, I go to my mother in law\'s house');
INSERT INTO phrases VALUES(NULL, 'madeir zan\'am', 'my mother-in-law');
INSERT INTO phrases VALUES(NULL, 'heir saal', 'every year');
INSERT INTO phrases VALUES(NULL, 'Heir saal, be Hawaii mir\'am', 'Every year, I go to Hawaii');
INSERT INTO phrases VALUES(NULL, 'rooz\'ee', 'each day');
INSERT INTO phrases VALUES(NULL, 'rooz\'ee yek bar', 'once each day');
INSERT INTO phrases VALUES(NULL, 'yek bar', 'one time');
INSERT INTO phrases VALUES(NULL, 'Rooz\'ee yek bar be estakht mir\'am', 'I go to the pool once a day');
INSERT INTO phrases VALUES(NULL, 'rooz\'ee do bar', 'two times each day');
INSERT INTO phrases VALUES(NULL, 'heir do rooz yek bar', 'once every two days (every two days one time)');
INSERT INTO phrases VALUES(NULL, 'hafte\'ee', 'each week');
INSERT INTO phrases VALUES(NULL, 'Hafte\'ee yek bar, be kelaase yoga mir\'am', 'Once a week, I go to yoga class');
INSERT INTO phrases VALUES(NULL, 'Heir do hafte yek bar', 'Once every two weeks');
INSERT INTO phrases VALUES(NULL, 'Heir do hafte yek bar, be khune\'ye doost\'am mir\'am', 'Every other week, I go to my friend\'s house');
INSERT INTO phrases VALUES(NULL, 'maa\'hee', 'each month');
INSERT INTO phrases VALUES(NULL, 'maa\'hee yek bar', 'once a month');
INSERT INTO phrases VALUES(NULL, 'Maa\'hee yek bar, be Dallas mir\'am', 'Once a month, I go to Dallas');
INSERT INTO phrases VALUES(NULL, 'Heir chahar maa yek bar, be Dallas mir\'am', 'Every four months, I go to Dallas');
INSERT INTO phrases VALUES(NULL, 'Saal\'ee yek bar, be Hawaii mir\'am', 'Once a year, I go to Hawaii');
INSERT INTO phrases VALUES(NULL, 'Heir rooz aashpazi mikhon\'am', 'Every day I cook');
INSERT INTO phrases VALUES(NULL, 'Heir do rooz yek bar aashpazi mikhon\'am ', 'Every other day I cook');
INSERT INTO phrases VALUES(NULL, 'Heir chand vakht yek bar aashpazi mikhon\'i?', 'How often do you cook?');
INSERT INTO phrases VALUES(NULL, 'Heir chand vakht yek bar be Dallas mir\'i?', 'How often do you go to Dallas?');
INSERT INTO phrases VALUES(NULL, 'Heir do se hafte yek bar be Dallas mir\'am', 'Every two or three weeks, I go to Dallas');
INSERT INTO phrases VALUES(NULL, 'Daar\'am naahar mikhor\'am', 'I\'m (currently) eating lunch');
INSERT INTO phrases VALUES(NULL, 'Daar\'am mi\'am', 'I\'m (currently) coming');
INSERT INTO phrases VALUES(NULL, 'Daar\'i mia\'i?', 'Are you (currently) coming?');
INSERT INTO phrases VALUES(NULL, 'Daar\'e mia\'d', 'He/she is (currently) coming');
INSERT INTO phrases VALUES(NULL, 'Daar\'im mia\'im', 'We are (currently) coming');
INSERT INTO phrases VALUES(NULL, 'Daar\'in mia\'in', 'You are (currently) coming (plural/formal)');
INSERT INTO phrases VALUES(NULL, 'Daar\'an mi\'an', 'They are (currently) coming');
INSERT INTO phrases VALUES(NULL, 'Daar\'am mikhor\'am', 'I\'m (currently) eating');
INSERT INTO phrases VALUES(NULL, 'Daar\'e mikhor\'e', 'He/she is (currently) eating');
INSERT INTO phrases VALUES(NULL, 'Daar\'an mikhor\'an', 'They are (currently) eating');
INSERT INTO phrases VALUES(NULL, 'nishastan', 'to sit (infinitive)');
INSERT INTO phrases VALUES(NULL, 'sheen', 'sit (present stem)');
INSERT INTO phrases VALUES(NULL, 'misheen\'am', 'I sit');
INSERT INTO phrases VALUES(NULL, 'misheen\'i', 'you sit');
INSERT INTO phrases VALUES(NULL, 'besheen\'in', 'sit! (formal imperative)');
INSERT INTO phrases VALUES(NULL, 'Lotfan besheen\'in', 'Please sit (formal)');
INSERT INTO phrases VALUES(NULL, 'Befarma\'in besheen\'in', 'Please go ahead and sit (formal)');
INSERT INTO phrases VALUES(NULL, 'befarma\'in', 'please go ahead (formal)');
INSERT INTO phrases VALUES(NULL, 'besheen', 'sit! (imperative)');
INSERT INTO phrases VALUES(NULL, 'lotfan besheen', 'please sit');
INSERT INTO phrases VALUES(NULL, 'befarma besheen', 'please go ahead and sit');
INSERT INTO phrases VALUES(NULL, 'Lotfan inja besheen', 'Please sit here');
INSERT INTO phrases VALUES(NULL, 'nasheen', 'don\'t sit');
INSERT INTO phrases VALUES(NULL, 'Lotfan unja nasheen\'in', 'Please don\'t sit there (formal)');
INSERT INTO phrases VALUES(NULL, 'gozashtan', 'to put (infinitive)');
INSERT INTO phrases VALUES(NULL, 'zar', 'to put (present stem)');
INSERT INTO phrases VALUES(NULL, 'bezar', 'you put');
INSERT INTO phrases VALUES(NULL, 'Bezar rooye meez', 'Put it on the table');
INSERT INTO phrases VALUES(NULL, 'Bezar paayin', 'Put it down');
INSERT INTO phrases VALUES(NULL, 'Ketaab\'o bezar paayin', 'Put down the book');
INSERT INTO phrases VALUES(NULL, 'Ketaab\'o bezar rooye meez', 'Put the book on the table');
INSERT INTO phrases VALUES(NULL, 'na\'khord\'am', 'I didn\'t eat');
INSERT INTO phrases VALUES(NULL, 'Dirooz naahar na\'khord\'am', 'I didn\'t eat lunch yesterday');
INSERT INTO phrases VALUES(NULL, 'Emrooz naahar khord\'am', 'I ate lunch today');
INSERT INTO phrases VALUES(NULL, 'Daar\'i chi kar mikhon\'i?', 'What are you (currently) doing?');
INSERT INTO phrases VALUES(NULL, 'khor', 'eat (present stem)');
INSERT INTO phrases VALUES(NULL, 'lotfan bokhor', 'please eat');
INSERT INTO phrases VALUES(NULL, 'lotfan nakhor', 'please don\'t eat');
INSERT INTO phrases VALUES(NULL, 'sohbat keirdan', 'to speak (infinitive) (to do speech)');
INSERT INTO phrases VALUES(NULL, 'Babak sohbat keird', 'Babak spoke');
INSERT INTO phrases VALUES(NULL, 'In hafte, Clinton sohbat keird', 'This week, Clinton spoke');
INSERT INTO phrases VALUES(NULL, 'Man\'o to sohbat keird\'in', 'Me and you spoke');
INSERT INTO phrases VALUES(NULL, 'Ba madeir\'am sohbat mikhon\'am', 'I\'m speaking to my mom');
INSERT INTO phrases VALUES(NULL, 'Sohbat bokhon\'am?', 'Shall I speak?');
INSERT INTO phrases VALUES(NULL, 'Sohbat bokhon\'im', 'Let\'s talk');
INSERT INTO phrases VALUES(NULL, 'Sohbat bokhon\'an', 'Let them talk');
INSERT INTO phrases VALUES(NULL, 'Bebakhshid baraa\'ye farsi\'ye man, vali daar\'am sai mikhonam yaad begiram', 'Sorry for my Persian, but I\'m trying to learn');
INSERT INTO phrases VALUES(NULL, 'ye dun\'e dige', 'one more');
INSERT INTO phrases VALUES(NULL, 'do taa dige', 'two more');
INSERT INTO phrases VALUES(NULL, 'se taa dige', 'three more');
INSERT INTO phrases VALUES(NULL, 'as in va', 'this way');
INSERT INTO phrases VALUES(NULL, 'as un va', 'that way');
INSERT INTO phrases VALUES(NULL, 'khotkar', 'pen');
INSERT INTO phrases VALUES(NULL, 'medaat', 'pencil');
INSERT INTO phrases VALUES(NULL, 'paak-khon', 'eraser');
INSERT INTO phrases VALUES(NULL, 'zameen', 'Earth');
INSERT INTO phrases VALUES(NULL, 'mashghul bud\'am', 'I\'ve been busy (I was busy)');
INSERT INTO phrases VALUES(NULL, 'Allon se maa\'he ke to ro na\'did\'am', 'I haven\'t seen you in three months');
INSERT INTO phrases VALUES(NULL, 'jedi', 'really');
INSERT INTO phrases VALUES(NULL, 'Daar in se maa chi kar keird\'i?', 'What did you do in the last three months?');
INSERT INTO phrases VALUES(NULL, 'taghaaza keird\'am', 'applied');
INSERT INTO phrases VALUES(NULL, 'khob', 'well (filler word Ex. \'well first I ...\')');
INSERT INTO phrases VALUES(NULL, 'daaneshga', 'university');
INSERT INTO phrases VALUES(NULL, 'Khob aval, baraa\'ye daaneshga taghaaza keird\'am', 'Well first, I applied for university');
INSERT INTO phrases VALUES(NULL, 'baraa\'ye man', 'for me');
INSERT INTO phrases VALUES(NULL, 'baraa\'ye to', 'for you');
INSERT INTO phrases VALUES(NULL, 'reshte', 'subject');
INSERT INTO phrases VALUES(NULL, 'Baraa\'ye che reshte\'i', 'For what subject?');
INSERT INTO phrases VALUES(NULL, 'pezeshghi', 'med school');
INSERT INTO phrases VALUES(NULL, 'pezesh', 'physician');
INSERT INTO phrases VALUES(NULL, 'Gabul shod\'i?', 'Were you accepted?');
INSERT INTO phrases VALUES(NULL, 'Gabul shod\'am', 'I was accepted');
INSERT INTO phrases VALUES(NULL, 'mobarak baashe', 'congratulations');
INSERT INTO phrases VALUES(NULL, 'dige', 'other');
INSERT INTO phrases VALUES(NULL, 'Dige chi?', 'What else?');
INSERT INTO phrases VALUES(NULL, 'Dige chi kar keird\'i?', 'What else did you do?');
INSERT INTO phrases VALUES(NULL, 'Ba Ladan raft\'am Espanya', 'I went to Spain with Ladan');
INSERT INTO phrases VALUES(NULL, 'famil', 'family');
INSERT INTO phrases VALUES(NULL, 'Unja kheili famil daar\'e', 'He/she has a lot of family there');
INSERT INTO phrases VALUES(NULL, 'khosh behaal\'et', 'lucky for you');
INSERT INTO phrases VALUES(NULL, 'Koja\'ye Espanya?', 'Where in Spain?');
INSERT INTO phrases VALUES(NULL, 'ba-d (ba-d\'esh)', 'after/next/later');
INSERT INTO phrases VALUES(NULL, 'Aval raft\'im Barcelona, va ba-d raft\'im Madrid', 'First we went to Barcelona, then we went to Madrid');
INSERT INTO phrases VALUES(NULL, 'khaanevaade', 'family (alternative way to say famil)');
INSERT INTO phrases VALUES(NULL, 'Va khaanevaad\'am\'o did\'am', 'And I saw my family');
INSERT INTO phrases VALUES(NULL, 'kholee', 'a lot');
INSERT INTO phrases VALUES(NULL, 'kaif', 'delight');
INSERT INTO phrases VALUES(NULL, 'baaham', 'together');
INSERT INTO phrases VALUES(NULL, 'Baaham kholee kaif keird\'im', 'Together we had a delightful time');
INSERT INTO phrases VALUES(NULL, 'shanid\'am', 'I heard');
INSERT INTO phrases VALUES(NULL, 'Shanid\'am mia\'i Dallas', 'I heard you were coming to Dallas');
INSERT INTO phrases VALUES(NULL, 'Bale dorost\'e', 'Yes that\'s correct');
INSERT INTO phrases VALUES(NULL, 'Emshab miras\'am', 'I arrive tonight');
INSERT INTO phrases VALUES(NULL, 'Has kay mia\'i khune\'ye ma?', 'So when are you coming to our house?');
INSERT INTO phrases VALUES(NULL, 'Zud mia\'m, feirda chetor?', 'I will come soon, how about tomorrow?');
INSERT INTO phrases VALUES(NULL, 'Mia\'i baraa\'ye naahar?', 'Will you come for lunch?');
INSERT INTO phrases VALUES(NULL, 'zaamat', 'hard work/trouble');
INSERT INTO phrases VALUES(NULL, 'Na, zaamat nakeshid', 'No, don\'t go through the trouble');
INSERT INTO phrases VALUES(NULL, 'Zaamati nist', 'It\'s no trouble');
INSERT INTO phrases VALUES(NULL, 'migir\'im', 'we will get');
INSERT INTO phrases VALUES(NULL, 'Doost dar\'i ber\'im cinama?', 'Would you like to go to the cinema?');
INSERT INTO phrases VALUES(NULL, 'Che film\'ee?', 'What movie?');
INSERT INTO phrases VALUES(NULL, 'Fekr mikhonam Les Miserables faransavi\'e', 'I think Les Miserable is French');
INSERT INTO phrases VALUES(NULL, 'mig\'i', 'you say');
INSERT INTO phrases VALUES(NULL, 'Raast mig\'i', 'You\'re right (right you say)');
INSERT INTO phrases VALUES(NULL, 'Ba-d as naahar mir\'im cinama', 'After lunch we will go to the cinema');
INSERT INTO phrases VALUES(NULL, 'Piruz ham mia\'d?', 'Will Piruz also come?');
INSERT INTO phrases VALUES(NULL, 'hala na', 'not now');
INSERT INTO phrases VALUES(NULL, 'Ne\'midun\'am, hala bebin\'im', 'I don\'t know, we\'ll see');
INSERT INTO phrases VALUES(NULL, 'Bia be boos\'imet', 'Come so I can kiss you');
INSERT INTO phrases VALUES(NULL, 'del\'am', 'my heart');
INSERT INTO phrases VALUES(NULL, 'Del\'am baraa\'t tang shod\'e bud', 'I missed you (literal: My heart became tight for you)');
INSERT INTO phrases VALUES(NULL, 'Man ham hamintor', 'Me also');
INSERT INTO phrases VALUES(NULL, 'rha', 'way');
INSERT INTO phrases VALUES(NULL, 'Rha chetor bud?', 'How was the trip? (literal: how was the way)');
INSERT INTO phrases VALUES(NULL, 'Kheili tool keshid', 'It took a long time');
INSERT INTO phrases VALUES(NULL, 'too rha', 'on the way');
INSERT INTO phrases VALUES(NULL, 'Too rha tasaadof shod\'e bud', 'On the way an accident happened');
INSERT INTO phrases VALUES(NULL, 'ey vaay', 'oh no');
INSERT INTO phrases VALUES(NULL, 'Bad joor bud?', 'Was it bad?');
INSERT INTO phrases VALUES(NULL, 'esala', 'a saying (an expression)');
INSERT INTO phrases VALUES(NULL, 'Be esala \'fender bender\' bud', 'It would be called a \'fender bender\'');
INSERT INTO phrases VALUES(NULL, '\'Fender bender\' ya nee chi?', 'What is a fender bender?');
INSERT INTO phrases VALUES(NULL, 'khob ya nee', 'well it means');
INSERT INTO phrases VALUES(NULL, 'josee', 'trivial/insignificant');
INSERT INTO phrases VALUES(NULL, 'Khob ya nee josee bud', 'Well it means it was insignificant');
INSERT INTO phrases VALUES(NULL, 'khodara shokhr', 'thank god');
INSERT INTO phrases VALUES(NULL, 'maman-joon', 'grandmother');
INSERT INTO phrases VALUES(NULL, 'Maman-joon inja hast\'an?', 'Is grandma here?');
INSERT INTO phrases VALUES(NULL, 'hanooz', 'yet');
INSERT INTO phrases VALUES(NULL, 'Hanooz nayumid\'an', 'He/she didn\'t come yet');
INSERT INTO phrases VALUES(NULL, 'Emshab mi\'an', 'He/she will come tonight (formal/plural)');
INSERT INTO phrases VALUES(NULL, 'Ke baaham shaam bokhor\'im', 'So that we could have dinner together');
INSERT INTO phrases VALUES(NULL, 'Too khune ya birun?', 'In the house or out?');
INSERT INTO phrases VALUES(NULL, 'Na azizam, maman-joon shaam dorost keird\'am', 'No dear, grandma made dinner');
INSERT INTO phrases VALUES(NULL, 'Baaham chai bokhor\'im', 'Together let\'s have a tea');
INSERT INTO phrases VALUES(NULL, 'bah bah', 'yummy');
INSERT INTO phrases VALUES(NULL, 'michasbe', 'it sticks');
INSERT INTO phrases VALUES(NULL, 'Chai michasbe', 'Chai would really hit the spot (chai sticks)');
INSERT INTO phrases VALUES(NULL, 'Bah bah, allon cheghadre chai michasbe', 'Mmm, tea would really hit the spot right now');
INSERT INTO phrases VALUES(NULL, 'Dars mikhunam', 'I\'m studying');
INSERT INTO phrases VALUES(NULL, 'Dige chi?', 'What else?');
INSERT INTO phrases VALUES(NULL, 'Az break lezzat mibaram', 'I\'m enjoying my break');
INSERT INTO phrases VALUES(NULL, 'Neshaste poshte miz ba lebase zir', 'I\'m sitting at my desk in my underwear');
INSERT INTO phrases VALUES(NULL, 'Sharvaal', 'Pants');
INSERT INTO phrases VALUES(NULL, 'Daram miram kharide mive', 'I\'m going to buy groceries');
INSERT INTO phrases VALUES(NULL, 'Otobus migiram', 'I will take the bus');
INSERT INTO phrases VALUES(NULL, 'Piade migiram', 'I will walk');
INSERT INTO phrases VALUES(NULL, 'Cornfelakes baayad bekhabam', 'I need to buy cereal');
INSERT INTO phrases VALUES(NULL, 'Noon kharidam', 'I bought bread');
INSERT INTO phrases VALUES(NULL, 'Man emrooz Python khaham khund', 'I will study Python today');
INSERT INTO phrases VALUES(NULL, 'Bayad baraye mosahebe amade sham', 'I need to prepare for interviews');
INSERT INTO phrases VALUES(NULL, 'Donbale kar migardam', 'I am looking for a job');
INSERT INTO phrases VALUES(NULL, 'I want to be successful', 'Mikham moafagh basham');
INSERT INTO phrases VALUES(NULL, 'Maa be Toronto mirim', 'We are moving to Toronto');
INSERT INTO phrases VALUES(NULL, 'aghriban', 'almost');